import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('/admin/assesment');
  await page.getByRole('link', { name: ' RBKal' }).click();
  await page.getByRole('link', { name: ' RBKal' }).click();
  await page.getByRole('link', { name: 'Asesmen', exact: true }).click();
  await page.getByRole('heading', { name: 'Assesmen RBKAL' }).click();
  await page.getByRole('link', { name: ' Tambah Asesmen' }).click();
  await page.getByRole('heading', { name: 'Lembar Kerja Asesmen' }).click();
  await page.getByRole('combobox').selectOption('9901');
  await page.getByPlaceholder('YYYY').click();
  await page.getByPlaceholder('YYYY').fill('2028');
  await page.getByRole('radio', { name: 'Klasifikasi status IDM dalam dipertahankan dalam kategori Desa Mandiri. (Nilai' }).check();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan penjelasan...').fill('test');
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan rekomendasi...').fill('test');
  await page.getByRole('radio', { name: 'Kondisi desa pada tahun n-1 berdasarkan aplikasi Prodeskel dalam kategori Swakarya (Nilai: 3)', exact: true }).check();
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan penjelasan...').fill('test');
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan rekomendasi...').fill('test');
  await page.getByRole('radio', { name: 'Pemutakhiran menu data Sinkal 100 % (Nilai: 4)' }).check();
  await page.getByRole('row', { name: 'Pemutakhiran Data Profil Kalurahan (SINKAL) Pemutakhiran menu data Sinkal 100' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: 'Pemutakhiran Data Profil Kalurahan (SINKAL) Pemutakhiran menu data Sinkal 100' }).getByPlaceholder('Masukkan penjelasan...').fill('test');
  await page.getByRole('row', { name: 'Pemutakhiran Data Profil Kalurahan (SINKAL) Pemutakhiran menu data Sinkal 100' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: 'Pemutakhiran Data Profil Kalurahan (SINKAL) Pemutakhiran menu data Sinkal 100' }).getByPlaceholder('Masukkan penjelasan...').fill('testtest');
  await page.getByRole('row', { name: 'Pemutakhiran Data Profil Kalurahan (SINKAL) Pemutakhiran menu data Sinkal 100' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: 'Pemutakhiran Data Profil Kalurahan (SINKAL) Pemutakhiran menu data Sinkal 100' }).getByPlaceholder('Masukkan rekomendasi...').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhi 3 (tiga) jenis' }).check();
  await page.getByRole('row', { name: 'Tersedianya Dokumen Informasi' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: 'Tersedianya Dokumen Informasi' }).getByPlaceholder('Masukkan penjelasan...').fill('test');
  await page.getByRole('row', { name: 'Tersedianya Dokumen Informasi' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: 'Tersedianya Dokumen Informasi' }).getByPlaceholder('Masukkan rekomendasi...').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhi 4 (Empat) Indikator' }).check();
  await page.getByRole('row', { name: '2 Pengembangan Sistem' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: '2 Pengembangan Sistem' }).getByPlaceholder('Masukkan penjelasan...').fill('test');
  await page.getByRole('row', { name: '2 Pengembangan Sistem' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: '2 Pengembangan Sistem' }).getByPlaceholder('Masukkan rekomendasi...').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhi 3 s.d. 4 indikator' }).check();
  await page.getByRole('row', { name: '3 Penguatan Digitalisasi' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: '3 Penguatan Digitalisasi' }).getByPlaceholder('Masukkan penjelasan...').fill('test');
  await page.getByRole('row', { name: '3 Penguatan Digitalisasi' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: '3 Penguatan Digitalisasi' }).getByPlaceholder('Masukkan rekomendasi...').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhinya 7 s.d 8' }).check();
  await page.locator('textarea[name="jawab[4][14][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[4][14][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[4][14][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[4][14][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhinya 2 (dua) indikator dampak penguatan pengadaan barang dan jasa' }).check();
  await page.locator('textarea[name="jawab[5][22][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[5][22][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[5][22][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[5][22][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: '76- 100 % aset Kalurahan' }).check();
  await page.locator('textarea[name="jawab[6][25][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[6][25][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[6][25][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[6][25][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Capaian fisik 100% dan capaian keuangan lebih dari 90% (Nilai: 3)' }).check();
  await page.locator('textarea[name="jawab[7][26][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[7][26][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[7][26][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[7][26][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: '76 % - 100 % rangkaian' }).check();
  await page.locator('textarea[name="jawab[8][27][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[8][27][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[8][27][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[8][27][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhinya 2 (dua) kriteria' }).check();
  await page.locator('textarea[name="jawab[8][28][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[8][28][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[8][28][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[8][28][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Mekanisme pelaporan atas penerimaan gratifikasi telah terlembaga dengan baik' }).check();
  await page.locator('textarea[name="jawab[9][29][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[9][29][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[9][29][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[9][29][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terdapat saluran bagi masyarakat dalam pengawasan kinerja Pemerintah Kalurahan, dan masyarakat terlibat secara aktif dalam fungsi pengawasan melalui saluran tersebut. (Nilai: 4)', exact: true }).check();
  await page.locator('textarea[name="jawab[10][30][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[10][30][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[10][30][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[10][30][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Monitoring dan evaluasi telah' }).check();
  await page.locator('textarea[name="jawab[10][31][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[10][31][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[10][31][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[10][31][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: '76 % - 100 % Hasil pengawasan' }).check();
  await page.locator('textarea[name="jawab[10][32][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[10][32][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[10][32][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[10][32][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhinya 2 (dua) indikator dampak penguatan regulatif pemerintahan' }).check();
  await page.locator('textarea[name="jawab[11][33][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[11][33][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[11][33][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[11][33][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhinya 3 (tiga) indikator dampak pengisian pamong kalurahan yang transparan, objektif, akuntabel, dan bebas KKN (Nilai: 4)', exact: true }).check();
  await page.locator('textarea[name="jawab[12][36][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[12][36][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[12][36][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[12][36][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhinya 3-4 (tiga hingga' }).check();
  await page.locator('textarea[name="jawab[13][39][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[13][39][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[13][39][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[13][39][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Sosialisasi dilaksanakan secara reguler, diinformasikan melalui media informasi' }).check();
  await page.locator('textarea[name="jawab[14][44][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[14][44][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[14][44][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[14][44][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: '51 % - 75% Aparatur' }).check();
  await page.locator('textarea[name="jawab[14][45][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[14][45][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[14][45][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[14][45][rekomendasi]"]').fill('test');
  await page.locator('tr:nth-child(46) > td:nth-child(5) > .d-flex').click();
  await page.locator('textarea[name="jawab[15][46][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[15][46][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[15][46][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[15][46][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Terpenuhi 4-5 aspek pelayanan' }).check();
  await page.locator('textarea[name="jawab[15][51][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[15][51][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[15][51][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[15][51][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Pemerintah Kalurahan sudah' }).check();
  await page.locator('textarea[name="jawab[16][57][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[16][57][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[16][57][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[16][57][rekomendasi]"]').fill('test');
  await page.getByRole('radio', { name: 'Inovasi meningkatkan efisiensi operasional dan mengurangi biaya, tapi tidak' }).check();
  await page.locator('textarea[name="jawab[16][58][penjelasan]"]').click();
  await page.locator('textarea[name="jawab[16][58][penjelasan]"]').fill('test');
  await page.locator('textarea[name="jawab[16][58][rekomendasi]"]').click();
  await page.locator('textarea[name="jawab[16][58][rekomendasi]"]').fill('test');

  // await page.getByRole('button', { name: 'Kirim' }).click();
  // await page.getByRole('radio', { name: 'Telah dilaksanakan monitoring' }).check();
  // await page.getByRole('button', { name: 'Kirim' }).click();
  // await page.getByRole('radio', { name: 'Terdapat saluran bagi masyarakat dalam pengawasan kinerja Pemerintah Kalurahan, dan masyarakat terlibat secara aktif dalam fungsi pengawasan melalui saluran tersebut. (Nilai: 4)', exact: true }).check();
  // await page.locator('textarea[name="jawab[10][30][penjelasan]"]').click();
  // await page.locator('textarea[name="jawab[10][30][penjelasan]"]').fill('test');
  // await page.locator('textarea[name="jawab[10][30][rekomendasi]"]').click();
  // await page.locator('textarea[name="jawab[10][30][rekomendasi]"]').fill('test');

  await page.getByRole('button', { name: 'Kirim' }).click();
  await page.getByRole('heading', { name: 'Berhasil!' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('link', { name: ' Lihat & Edit' }).first().click();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan penjelasan...').fill('test edit');
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: '1 Penguatan Pengelolaan Data' }).getByPlaceholder('Masukkan rekomendasi...').fill('test edit');
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan penjelasan...').click();
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan penjelasan...').fill('test edit');
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan rekomendasi...').click();
  await page.getByRole('row', { name: 'Pemutakhiran data Profil Kalurahan (Prodeskel) Kondisi desa pada tahun n-1' }).getByPlaceholder('Masukkan rekomendasi...').fill('test edit');
  await page.getByRole('radio', { name: 'Kondisi desa pada tahun n-1 berdasarkan aplikasi Prodeskel dalam kategori Swasembada (Nilai: 4)', exact: true }).check();
  await page.getByRole('button', { name: 'Kirim' }).click();
  await page.getByRole('heading', { name: 'Berhasil!' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('row', { name: '1 kalurahan1-testing 2028 TAHUNAN' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Tutup' }).click();
  await page.getByRole('row', { name: '1 kalurahan1-testing 2028 TAHUNAN' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Iya, hapus' }).click();
});