import { test, expect } from '@playwright/test';

// test.use({
//   storageState: 'storageState.json'
// });

test('Kalurahan-Page', async ({ page }) => {
  await page.goto('/admin/kalurahan');
  await page.getByRole('link', { name: 'Kalurahan', exact: true }).click();
  await page.getByRole('link', { name: /Data kalurahan/i }).click();
  await page.getByRole('heading', { name: 'Data Kalurahan' }).click();
  await page.getByText('Kalurahan > Data Kalurahan').click();
  await page.getByRole('heading', { name: 'Daftar Kalurahan' }).click();
  await page.getByRole('link', { name: /Lihat data/i }).first().click();
  await page.waitForTimeout(500);
  await page.getByRole('link', { name: ' SDM' }).click();
  await page.getByRole('link', { name: ' SDM' }).click();
  await page.getByRole('link', { name: 'Pamong' }).click();
  await page.getByRole('heading', { name: 'Data Pamong' }).click();
  await page.getByRole('link', { name: 'Dukuh' }).click();
  await page.getByRole('heading', { name: 'Data Dukuh' }).click();
  await page.getByRole('link', { name: 'Staff' }).click();
  await page.getByRole('heading', { name: 'Data Staff' }).click();
  await page.getByRole('link', { name: 'Bamuskal' }).click();
  await page.getByRole('heading', { name: 'Data Bamuskal' }).click();
  await page.getByRole('link', { name: 'Rekap Presensi' }).click();
  await page.getByText('Sinkal SDM Rekap Presensi').click();
  await page.getByRole('link', { name: 'Presensi', exact: true }).click();
  await page.getByRole('heading', { name: 'Data Presensi' }).click();
  await page.getByRole('link', { name: ' Data Wilayah' }).click();
  await page.getByRole('link', { name: 'Wilayah', exact: true }).click();
  await page.getByRole('heading', { name: 'Peta Wilayah Kalurahan' }).click();
  await page.getByRole('link', { name: 'Profil Kalurahan' }).click();
  await page.getByText('Sinkal Data Wilayah Wilayah').click();
  await page.getByRole('link', { name: 'Tipologi Kalurahan' }).click();
  await page.getByRole('heading', { name: 'Tipologi Kalurahan' }).click();
  await page.getByRole('link', { name: 'Luas Wilayah' }).click();
  await page.getByRole('heading', { name: 'Luas Wilayah Kalurahan' }).click();
  await page.getByRole('link', { name: 'Orbitasi' }).click();
  await page.getByRole('heading', { name: 'Orbitasi Wilayah Kalurahan' }).click();
  await page.getByRole('link', { name: 'Kependudukan' }).click();
  await page.getByRole('heading', { name: 'Data Pertumbuhan Penduduk' }).click();
  await page.getByRole('link', { name: 'Pedukuhan' }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan' }).click();
  await page.getByRole('link', { name: 'Jenis Kelamin' }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan' }).click();
  await page.getByRole('link', { name: 'Usia', exact: true }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan Usia' }).click();
  await page.getByRole('link', { name: 'Kelompok Usia Produktif' }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan' }).click();
  await page.getByRole('link', { name: 'Agama' }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan' }).click();
  await page.getByRole('link', { name: 'Status Perkawinan' }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan' }).click();
  await page.getByRole('link', { name: 'Jenjang Pendidikan' }).click();
  await page.getByRole('heading', { name: 'Data Penduduk Berdasarkan' }).click();
  await page.getByRole('link', { name: 'Kesejahteraan' }).click();
  await page.getByRole('heading', { name: 'Data Tingkat Kesejahteraan' }).click();
  await page.getByRole('link', { name: 'Pekerjaan' }).click();
  await page.getByRole('heading', { name: 'Data Pekerjaan' }).click();
  await page.getByRole('link', { name: 'Sarana dan Prasarana' }).click();
  await page.getByRole('heading', { name: 'Data Sarana Kesehatan' }).click();
  await page.getByRole('link', { name: 'Pendidikan' }).click();
  await page.getByRole('heading', { name: 'Data Sarana Pendidikan' }).click();
  await page.getByRole('link', { name: 'Peribadatan' }).click();
  await page.getByRole('heading', { name: 'Data Sarana Ibadah' }).click();
  await page.getByRole('link', { name: 'Transportasi' }).click();
  await page.getByRole('heading', { name: 'Data Prasarana Transportasi' }).click();
  await page.getByRole('link', { name: 'Kebersihan' }).click();
  await page.getByRole('heading', { name: 'Data Prasarana Kebersihan' }).click();
  await page.getByRole('link', { name: 'Sanitasi dan Irigasi' }).click();
  await page.getByRole('heading', { name: 'Data Prasarana Sanitasi dan' }).click();
  await page.getByRole('link', { name: ' APBKAL' }).click();
  await page.getByRole('link', { name: 'Pendapatan' }).click();
  await page.getByRole('heading', { name: 'Statistik Data Pendapatan' }).click();
  await page.getByRole('link', { name: 'Pengeluaran' }).click();
  await page.getByRole('heading', { name: 'Statistik Data Pengeluaran' }).click();
  await page.getByRole('link', { name: 'Siskeudes' }).click();
  await page.getByRole('heading', { name: 'Upload Laporan Siskeudes' }).click();
  await page.getByRole('link', { name: ' Lembaga' }).click();
  await page.getByRole('heading', { name: 'Data Lembaga Masyarakat' }).click();
  await page.getByRole('link', { name: ' Layanan' }).click();
  await page.getByRole('heading', { name: 'Data Pelayanan Publik' }).click();
  await page.getByRole('link', { name: ' Jagawarga' }).click();
  await page.getByRole('link', { name: 'Omah Jagawarga' }).click();
  await page.getByRole('heading', { name: 'Data Omah Jagawarga' }).click();
  await page.getByRole('link', { name: 'Kelompok Jagawarga' }).click();
  await page.getByRole('heading', { name: 'Data Kelompok Jagawarga' }).click();
  await page.getByRole('link', { name: 'Laporan Kegiatan Jagawarga' }).click();
  await page.getByRole('heading', { name: 'Data Laporan Kegiatan' }).click();
  await page.getByRole('link', { name: ' Pengaduan' }).click();
  await page.getByRole('heading', { name: 'Data Pengaduan' }).click();
  await page.getByRole('link', { name: ' Peladi Makarti' }).click();
  await page.getByRole('link', { name: 'Peserta' }).click();
  await page.getByRole('heading', { name: 'Data Tamu' }).click();
  await page.getByRole('link', { name: 'Antar Kerja' }).click();
  await page.getByRole('heading', { name: 'Data Tamu Antar Kerja' }).click();
  await page.getByRole('link', { name: 'Pelatihan Kerja' }).click();
  await page.getByRole('heading', { name: 'Data Tamu Pelatihan Kerja' }).click();
  await page.getByRole('link', { name: 'Perluasan Kerja' }).click();
  await page.getByRole('heading', { name: 'Data Tamu Perluasan Kerja' }).click();
  await page.getByRole('link', { name: 'Hubungan Industrial' }).click();
  await page.getByRole('heading', { name: 'Data Tamu Hubungan Industrial' }).click();
  await page.getByRole('link', { name: 'Jaminan Sosial' }).click();
  await page.getByRole('heading', { name: 'Data Tamu Jaminan Sosial' }).click();
  await page.getByRole('link', { name: 'Rekap Ketenagakerjaan' }).click();
  await page.getByRole('heading', { name: 'Rekap Ketenagakerjaan' }).click();
  await page.getByRole('link', { name: ' RBKal' }).click();
  await page.getByRole('link', { name: 'Rencana Aksi' }).first().click();
  await page.getByRole('heading', { name: 'Rencana Aksi' }).click();
  await page.getByRole('link', { name: 'IKM' }).click();
  await page.getByRole('heading', { name: 'Data Indeks Kepuasan' }).click();
  await page.getByRole('link', { name: 'Assesmen' }).first().click();
  await page.getByRole('heading', { name: 'Assesmen RBKAL' }).click();
  await page.getByRole('link', { name: 'Evaluasi Kualitas Belanja' }).click();
  await page.getByRole('heading', { name: 'Evaluasi Kualitas Belanja' }).click();
  await page.getByRole('link', { name: ' RPMKal' }).click();
  await page.getByRole('link', { name: 'Capaian Sasaran' }).click();
  await page.getByRole('heading', { name: 'Capaian Sasaran' }).click();
  // await page.getByRole('link', { name: 'Assesmen' }).nth(1).click();
  // await page.getByRole('link', { name: 'Rencana Aksi' }).nth(1).click();
  // await page.getByRole('link', { name: 'Perencanaan' }).click();
  // await page.getByRole('link', { name: 'Rencana Aksi' }).nth(1).click();
  // await page.getByRole('link', { name: 'Pelaksanaan' }).click();
  await page.getByRole('img', { name: 'Back' }).click();
  await page.getByRole('heading', { name: 'Data Kalurahan' }).click();
});