import { test, expect } from '@playwright/test';

// test.use({
//   storageState: 'storageState.json'
// });

test('test', async ({ page }) => {
  await page.goto('/admin/laporan');
  await page.getByRole('link', { name: 'Kalurahan', exact: true }).click();
  await page.getByRole('link', { name: 'Laporan' }).click();
  await page.getByRole('heading', { name: 'Laporan' }).click();
  await page.getByText('Kalurahan > Laporan').click();
  await page.getByRole('heading', { name: 'Pencarian' }).click();
  await page.locator('#data').selectOption('keaktifan');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Keaktifan' }).click();
  await page.locator('#data').selectOption('pegawai');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Kepegawaian' }).click();
  await page.locator('#data').selectOption('du-wilayah');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Wilayah' }).click();
  await page.locator('#data').selectOption('du-pertumbuhan-penduduk');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Pertumbuhan' }).click();
  await page.locator('#data').selectOption('du-dusun');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Pedukuhan tahun' }).click();
  await page.locator('#data').selectOption('du-usia');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Penduduk' }).click();
  await page.locator('#data').selectOption('du-angkatan-kerja');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Kelompok usia' }).click();
  await page.locator('#data').selectOption('du-agama');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Agama tahun' }).click();
  await page.locator('#data').selectOption('du-status-kawin');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Status perkawinan' }).click();
  await page.locator('#data').selectOption('du-pendidikan');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Jenjang' }).click();
  await page.locator('#data').selectOption('du-kesejahteraan');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Tingkat' }).click();
  await page.locator('#data').selectOption('du-pekerjaan');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Pekerjaan' }).click();
  await page.locator('#data').selectOption('du-sarana');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Sarana tahun' }).click();
  await page.locator('#data').selectOption('du-prasarana');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Umum - Prasarana' }).click();
  await page.locator('#data').selectOption('pendapatan');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data APBKAL tahun' }).click();
  await page.locator('#data').selectOption('pengeluaran');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data APBKAL tahun' }).click();
  await page.locator('#data').selectOption('lembaga-layanan');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Data Lembaga Masyarakat dan' }).click();
  await page.locator('#data').selectOption('jagawarga');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Jagawarga' }).click();
  await page.locator('#data').selectOption('jagawarga-sarpras');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Jagawarga' }).click();
  await page.locator('#data').selectOption('jagawarga-omah');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Jagawarga' }).click();
  await page.locator('#data').selectOption('jagawarga-omah-sarpras');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Jagawarga' }).click();
  await page.locator('#data').selectOption('peladi-makarti');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Peladi Makarti' }).click();
  await page.locator('#kabupaten').selectOption('01002');
  await page.locator('#data').selectOption('pendapatan');
  await page.waitForTimeout(500);
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByText('Showing 1 to 10 of 86 entries').click();
  await page.locator('#kecamatan').selectOption('01002017');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByText('Showing 1 to 5 of 5 entries').click();
  await page.locator('#kelurahan').selectOption('393');
  await page.getByRole('button', { name: 'Tampilkan' }).click();
  await page.getByRole('heading', { name: 'Rasio Kemandirian APBKAL' }).click();
});