import { test, expect } from '@playwright/test';

// test.use({
//   storageState: 'storageState.json'
// });

test('test', async ({ page }) => {
  await page.goto('/admin/rpmkal-pelaksanaan');
  await page.getByRole('link', { name: ' RPMKal' }).click();
  await page.getByRole('link', { name: ' RPMKal' }).click();
  await page.getByRole('link', { name: 'Rencana Aksi' }).nth(1).click();
  await page.getByRole('link', { name: 'Rencana Aksi' }).nth(1).click();
  await page.getByRole('link', { name: 'Pelaksanaan' }).click();
  await page.getByText('Sinkal Testing 1 RPMKal Aksi').click();
  await page.getByRole('heading', { name: 'Aksi Pelaksanaan' }).click();
  await page.getByRole('button', { name: ' Tambah Pelaksanaan' }).click();
  await page.getByRole('combobox').selectOption('2021');
  await page.getByRole('button', { name: 'Tambah' }).click();
  await page.getByRole('heading', { name: 'Tambah Kegiatan' }).click();
  await page.getByRole('combobox').nth(1).selectOption('1');
  await page.getByRole('combobox').nth(2).selectOption('1');
  await page.getByRole('button', { name: 'Tambah Kegiatan' }).click();
  await page.getByRole('button', { name: 'Tambah Aktivitas' }).click();
  await page.getByRole('dialog', { name: 'Tambah Aktivitas' }).getByRole('combobox').selectOption('1');
  await page.getByRole('textbox', { name: 'Masukan Lokasi Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Lokasi Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Masukan Volume').click();
  await page.getByPlaceholder('Masukan Volume').fill('5');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Satuan Volume' }).click();
  await page.getByRole('textbox', { name: 'Masukan Satuan Volume' }).fill('100');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('radio').nth(1).check();
  await page.getByRole('textbox', { name: 'Masukan Keterangan Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keterangan Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Faktor Pendukung' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Pendukung' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('button', { name: 'Tambahkan Aktivitas' }).click();
  await page.getByRole('button', { name: 'Tambah', exact: true }).click();
  await page.getByRole('heading', { name: 'Tambah Kegiatan' }).click();
  await page.getByRole('combobox').nth(1).selectOption('5');
  await page.getByRole('combobox').nth(2).selectOption('16');
  await page.getByRole('button', { name: 'Tambah Kegiatan' }).click();
  await page.locator('#heading-16').getByRole('button', { name: 'Tambah Aktivitas' }).click();
  await page.getByRole('dialog', { name: 'Tambah Aktivitas' }).getByRole('combobox').selectOption('132');
  await page.getByRole('textbox', { name: 'Masukan Lokasi Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Lokasi Pelaksanaan' }).fill('test');
  await page.getByPlaceholder('Masukan Volume').click();
  await page.getByPlaceholder('Masukan Volume').fill('5');
  await page.getByRole('textbox', { name: 'Masukan Satuan Volume' }).click();
  await page.getByRole('textbox', { name: 'Masukan Satuan Volume' }).fill('15');
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).fill('test');
  await page.getByRole('radio').first().check();
  await page.getByRole('textbox', { name: 'biaya' }).click();
  await page.getByRole('textbox', { name: 'biaya' }).fill('20.0000');
  await page.locator('b').filter({ hasText: 'Biaya Rp Sumber Dana -- Pilih' }).getByRole('combobox').selectOption('11');
  await page.getByRole('checkbox', { name: 'Swakelola' }).check();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('radio').nth(1).check();
  await page.getByRole('textbox', { name: 'Masukan Keterangan Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keterangan Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Faktor Pendukung' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Pendukung' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('button', { name: 'Tambahkan Aktivitas' }).click();
  await page.locator('#heading-16').getByRole('button', { name: 'Tambah Aktivitas' }).click();
  await page.getByRole('dialog', { name: 'Tambah Aktivitas' }).getByRole('combobox').selectOption('133');
  await page.getByRole('textbox', { name: 'Masukan Lokasi Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Lokasi Pelaksanaan' }).fill('test');
  await page.getByPlaceholder('Masukan Volume').click();
  await page.getByPlaceholder('Masukan Volume').fill('1');
  await page.getByRole('textbox', { name: 'Masukan Satuan Volume' }).click();
  await page.getByRole('textbox', { name: 'Masukan Satuan Volume' }).fill('2');
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).fill('test');
  await page.getByRole('radio').first().check();
  await page.getByRole('textbox', { name: 'biaya' }).click();
  await page.getByRole('textbox', { name: 'biaya' }).fill('50.0000');
  await page.locator('b').filter({ hasText: 'Biaya Rp Sumber Dana -- Pilih' }).getByRole('combobox').selectOption('5');
  await page.locator('b > div:nth-child(3) > div').first().click();
  await page.getByRole('checkbox', { name: 'Swakelola' }).check();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('radio').nth(1).check();
  await page.getByRole('textbox', { name: 'Masukan Keterangan Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keterangan Pelaksanaan' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('textbox', { name: 'Masukan Faktor Pendukung' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Pendukung' }).fill('test');
  await page.waitForTimeout(500);
  await page.getByRole('button', { name: 'Tambahkan Aktivitas' }).click();

  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).click();
  await page.getByRole('textbox', { name: 'Masukan Keluaran Pelaksanaan' }).fill('tyest edit');
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).click();
  await page.getByRole('textbox', { name: 'Masukan Faktor Penghambat' }).fill('tyest edit');
  await page.getByRole('button', { name: 'Simpan', exact: true }).click();

  await page.getByRole('button', { name: 'Simpan Pelaksanaan' }).click();
  await page.getByRole('heading', { name: 'Berhasil!' }).click();
  await page.getByRole('button', { name: 'Tutup' }).click();
  await page.getByRole('link', { name: 'Lihat Data' }).first().click();
  await page.getByRole('heading', { name: 'Lihat Pelaksanaan' }).click();
  await page.getByRole('link', { name: 'Kembali' }).click();

  const row = page.getByRole('row').filter({
    hasText: '2021'
  });

  await row.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('button', { name: 'Tutup' }).click();
  await row.getByRole('button', { name: 'Hapus' }).click();
  await page.getByRole('button', { name: 'Iya, hapus' }).click();
});