import { test, expect } from '@playwright/test';

test.use({
    storageState: 'storageState.json'
});

test('test-draf', async ({ page }) => {
    await page.goto('/admin/rpmkal-assesmen-asesor');
    await page.getByRole('button', { name: ' Tambah Assesmen' }).click();
    await page.getByRole('heading', { name: 'Lembar Kerja Asesmen' }).click();
    await page.getByRole('combobox').first().selectOption('366');
    await page.getByRole('combobox').nth(1).selectOption('2028');
    await page.getByRole('button', { name: 'Kirim' }).click();
    await page.getByText('Kriterias.1.1.kriteria wajib').click();
    await page.getByText('Jawabans.1.1.jawaban wajib').click();
    await page.getByText('Rekomendasis.1.1.rekomendasi').click();
    await page.getByText('Kriterias.1.2.kriteria wajib').click();
    await page.getByText('Jawabans.1.2.jawaban wajib').click();
    await page.getByText('Rekomendasis.1.2.rekomendasi').click();
    await page.getByText('Kriterias.1.3.kriteria wajib').click();
    await page.getByText('Jawabans.1.3.jawaban wajib').click();
    await page.getByText('Rekomendasis.1.3.rekomendasi').click();
    await page.getByText('Kriterias.1.4.kriteria wajib').click();
    await page.getByText('Jawabans.1.4.jawaban wajib').click();
    await page.getByText('Rekomendasis.1.4.rekomendasi').click();
    await page.getByText('Kriterias.1.5.kriteria wajib').click();
    await page.getByText('Jawabans.1.5.jawaban wajib').click();
    await page.getByText('Rekomendasis.1.5.rekomendasi').click();
    await page.getByText('Kriterias.1.6.kriteria wajib').click();
    await page.getByText('Jawabans.1.6.jawaban wajib').click();
    await page.getByText('Rekomendasis.1.6.rekomendasi').click();
    await page.getByText('Kriterias.2.7.kriteria wajib').click();
    await page.getByText('Jawabans.2.7.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.7.rekomendasi').click();
    await page.getByText('Kriterias.2.8.kriteria wajib').click();
    await page.getByText('Jawabans.2.8.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.8.rekomendasi').click();
    await page.getByText('Kriterias.2.9.kriteria wajib').click();
    await page.getByText('Jawabans.2.9.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.9.rekomendasi').click();
    await page.getByText('Kriterias.2.10.kriteria wajib').click();
    await page.getByText('Jawabans.2.10.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.10.rekomendasi').click();
    await page.getByText('Kriterias.2.11.kriteria wajib').click();
    await page.getByText('Jawabans.2.11.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.11.rekomendasi').click();
    await page.getByText('Kriterias.2.12.kriteria wajib').click();
    await page.getByText('Jawabans.2.12.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.12.rekomendasi').click();
    await page.getByText('Kriterias.2.13.kriteria wajib').click();
    await page.getByText('Jawabans.2.13.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.13.rekomendasi').click();
    await page.getByText('Kriterias.2.14.kriteria wajib').click();
    await page.getByText('Jawabans.2.14.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.14.rekomendasi').click();
    await page.getByText('Kriterias.2.15.kriteria wajib').click();
    await page.getByText('Jawabans.2.15.jawaban wajib').click();
    await page.getByText('Rekomendasis.2.15.rekomendasi').click();
    await page.getByText('Kriterias.3.16.kriteria wajib').click();
    await page.getByText('Jawabans.3.16.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.16.rekomendasi').click();
    await page.getByText('Kriterias.3.17.kriteria wajib').click();
    await page.getByText('Jawabans.3.17.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.17.rekomendasi').click();
    await page.getByText('Kriterias.3.21.kriteria wajib').click();
    await page.getByText('Jawabans.3.21.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.21.rekomendasi').click();
    await page.getByText('Kriterias.3.18.kriteria wajib').click();
    await page.getByText('Jawabans.3.18.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.18.rekomendasi').click();
    await page.getByText('Kriterias.3.22.kriteria wajib').click();
    await page.getByText('Jawabans.3.22.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.22.rekomendasi').click();
    await page.getByText('Kriterias.3.19.kriteria wajib').click();
    await page.getByText('Jawabans.3.19.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.19.rekomendasi').click();
    await page.getByText('Kriterias.3.23.kriteria wajib').click();
    await page.getByText('Jawabans.3.23.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.23.rekomendasi').click();
    await page.getByText('Kriterias.3.20.kriteria wajib').click();
    await page.getByText('Jawabans.3.20.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.20.rekomendasi').click();
    await page.getByText('Kriterias.3.24.kriteria wajib').click();
    await page.getByText('Jawabans.3.24.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.24.rekomendasi').click();
    await page.getByText('Kriterias.3.49.kriteria wajib').click();
    await page.getByText('Jawabans.3.49.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.49.rekomendasi').click();
    await page.getByText('Indikator lain.3.49.indikator').click();
    await page.getByText('Kriterias.3.48.kriteria wajib').click();
    await page.getByText('Jawabans.3.48.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.48.rekomendasi').click();
    await page.getByText('Kriterias.3.25.kriteria wajib').click();
    await page.getByText('Jawabans.3.25.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.25.rekomendasi').click();
    await page.getByText('Kriterias.3.26.kriteria wajib').click();
    await page.getByText('Jawabans.3.26.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.26.rekomendasi').click();
    await page.getByText('Kriterias.3.27.kriteria wajib').click();
    await page.getByText('Jawabans.3.27.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.27.rekomendasi').click();
    await page.getByText('Kriterias.3.28.kriteria wajib').click();
    await page.getByText('Jawabans.3.28.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.28.rekomendasi').click();
    await page.getByText('Kriterias.3.50.kriteria wajib').click();
    await page.getByText('Jawabans.3.50.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.50.rekomendasi').click();
    await page.getByText('Indikator lain.3.50.indikator').click();
    await page.getByText('Kriterias.3.29.kriteria wajib').click();
    await page.getByText('Jawabans.3.29.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.29.rekomendasi').click();
    await page.getByText('Kriterias.3.30.kriteria wajib').click();
    await page.getByText('Jawabans.3.30.jawaban wajib').click();
    await page.getByText('Rekomendasis.3.30.rekomendasi').click();
    await page.getByText('Kriterias.4.31.kriteria wajib').click();
    await page.getByText('Jawabans.4.31.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.31.rekomendasi').click();
    await page.getByText('Rekomendasis.4.31.rekomendasi').click();
    await page.getByText('Jawabans.4.32.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.32.rekomendasi').click();
    await page.getByText('Kriterias.4.33.kriteria wajib').click();
    await page.getByText('Jawabans.4.33.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.33.rekomendasi').click();
    await page.getByText('Kriterias.4.34.kriteria wajib').click();
    await page.getByText('Jawabans.4.34.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.34.rekomendasi').click();
    await page.getByText('Kriterias.4.35.kriteria wajib').click();
    await page.getByText('Jawabans.4.35.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.35.rekomendasi').click();
    await page.getByText('Kriterias.4.36.kriteria wajib').click();
    await page.getByText('Jawabans.4.36.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.36.rekomendasi').click();
    await page.getByText('Kriterias.4.37.kriteria wajib').click();
    await page.getByText('Jawabans.4.37.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.37.rekomendasi').click();
    await page.getByText('Kriterias.4.38.kriteria wajib').click();
    await page.getByText('Jawabans.4.38.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.38.rekomendasi').click();
    await page.getByText('Kriterias.4.39.kriteria wajib').click();
    await page.getByText('Jawabans.4.39.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.39.rekomendasi').click();
    await page.getByText('Kriterias.4.40.kriteria wajib').click();
    await page.getByText('Jawabans.4.40.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.40.rekomendasi').click();
    await page.getByText('Kriterias.4.41.kriteria wajib').click();
    await page.getByText('Jawabans.4.41.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.41.rekomendasi').click();
    await page.getByText('Kriterias.4.42.kriteria wajib').click();
    await page.getByText('Jawabans.4.42.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.42.rekomendasi').click();
    await page.getByText('Kriterias.4.43.kriteria wajib').click();
    await page.getByText('Jawabans.4.43.jawaban wajib').click();
    await page.getByText('Rekomendasis.4.43.rekomendasi').click();
    await page.getByText('Kriterias.5.44.kriteria wajib').click();
    await page.getByText('Jawabans.5.44.jawaban wajib').click();
    await page.getByText('Rekomendasis.5.44.rekomendasi').click();
    await page.getByText('Kriterias.5.45.kriteria wajib').click();
    await page.getByText('Jawabans.5.45.jawaban wajib').click();
    await page.getByText('Jawabans.5.45.jawaban wajib').click();
    await page.getByText('Kriterias.5.46.kriteria wajib').click();
    await page.getByText('Jawabans.5.46.jawaban wajib').click();
    await page.getByText('Rekomendasis.5.46.rekomendasi').click();
    await page.getByText('Kriterias.5.47.kriteria wajib').click();
    await page.getByText('Jawabans.5.47.jawaban wajib').click();
    await page.getByText('Rekomendasis.5.47.rekomendasi').click();
    await page.getByRole('radio', { name: 'Persentase balita yang diukur pertumbuhan dan dilaporkan ke puskesmas dibandingkan seluruh sasaran balita di wilayah sebesar >90% (Nilai: 4)', exact: true }).click();
    await page.locator('textarea[name="jawabans.1.1.jawaban"]').click();
    await page.locator('textarea[name="jawabans.1.1.jawaban"]').fill('test');
    await page.locator('textarea[name="rekomendasis.1.1.rekomendasi"]').click();
    await page.locator('textarea[name="rekomendasis.1.1.rekomendasi"]').fill('test');
    await page.getByRole('button', { name: 'Simpan Draf' }).click();
    await page.getByRole('heading', { name: 'Draf Disimpan!' }).click();
    await page.getByRole('button', { name: 'Tutup' }).click();
    await page.getByRole('link', { name: 'Lanjutkan Draf' }).click();
    await page.getByRole('radio', { name: 'Tersedia dokumen rencana aksi penanganan stunting kalurahan, selaras dengan Rencana Aksi Daerah (Nilai: 3)', exact: true }).click();
    await page.locator('textarea[name="jawabans.1.2.jawaban"]').click();
    await page.locator('textarea[name="jawabans.1.2.jawaban"]').fill('test');
    await page.locator('textarea[name="rekomendasis.1.2.rekomendasi"]').click();
    await page.locator('textarea[name="rekomendasis.1.2.rekomendasi"]').fill('test');
    await page.getByRole('button', { name: 'Kirim Asesmen' }).click();
    await page.getByRole('button', { name: 'Simpan Draf' }).click();
    await page.getByRole('heading', { name: 'Berhasil!' }).click();
    await page.getByRole('button', { name: 'Tutup' }).click();
    await page.getByRole('link', { name: 'Detail' }).first().click();
    await page.getByRole('heading', { name: 'Detail Assesmen' }).click();
    await page.getByText('Kalurahan Minomartani').click();
    await page.getByText('Tahun 2028').click();
    await page.locator('#tbl-parent-0').click();
    await page.getByRole('link', { name: 'Kembali' }).click();
    await page.getByRole('button', { name: 'Hapus Draf' }).click();
    await page.getByRole('button', { name: 'Batal' }).click();
    await page.getByRole('button', { name: 'Hapus Draf' }).click();
    await page.getByRole('button', { name: 'Hapus Assesmen' }).click();
    await page.getByRole('button', { name: 'Tutup' }).click();

});
